README.md, package.json
Github editor inserted invalid charactor.
=> Remove Invalid character.

karma.browsers.js, karma.conf.js, rollup.config.js
* rollup and karma configs should also be scared by eslint.
=> Apply code style to config files

.circleci/config.yml, karma.conf.js
* Forked pull requests are tested with only chrome and Firefox on CI.
=> Run tests on forked pull requests

README.md, docs/examples/helpers/vgl-polar-grid-helper.html, src/helpers/vgl-polar-grid-helper.js, src/index.js, test/vgl-polar-grid-helper.spec.js
=> Add a new polar grid helper component.

README.md, docs/examples/materials/vgl-mesh-basic-material.html, src/index.js, src/materials/vgl-mesh-basic-material.js, test/vgl-mesh-basic-material.spec.js
=> Add a new mesh basic material component.

docs/examples/materials/vgl-mesh-basic-material.html, docs/examples/materials/vgl-mesh-depth-material.html, docs/examples/reactive-rendering.html, src/index.js, src/materials/vgl-mesh-basic-material.js, src/materials/vgl-mesh-depth-material.js, test/vgl-mesh-depth-material.spec.js
=> Add a new mesh depth material component

README.md, docs/examples/materials/vgl-mesh-lambert-material.html, src/index.js, src/materials/vgl-mesh-lambert-material.js, test/vgl-mesh-lambert-material.spec.js
=> Add a new mesh lambert material component

README.md, docs/examples/materials/vgl-mesh-normal-material.html, src/index.js, src/materials/vgl-mesh-normal-material.js, test/vgl-mesh-normal-material.spec.js
=> Add a new mesh normal material component

README.md, docs/examples/materials/vgl-line-dashed-material.html, src/index.js, src/materials/vgl-line-dashed-material.js, src/objects/vgl-line.js, test/vgl-line-dashed-material.spec.js
=> Add a new line dashed material component

docs/examples/materials/vgl-mesh-basic-material.html, docs/examples/materials/vgl-mesh-depth-material.html, docs/examples/materials/vgl-mesh-lambert-material.html, docs/examples/materials/vgl-mesh-normal-material.html, docs/examples/materials/vgl-mesh-phong-material.html, docs/examples/materials/vgl-mesh-standard-material.html, src/index.js, src/materials/vgl-mesh-phong-material.js, test/vgl-mesh-phong-material.spec.js
=> Add a new mesh phong material component

docs/examples/materials/vgl-mesh-toon-material.html, src/index.js, src/materials/vgl-mesh-toon-material.js, test/vgl-mesh-toon-material.spec.js
=> Add a new mesh toon material component

docs/examples/materials/vgl-mesh-physical-material.html, src/index.js, src/materials/vgl-mesh-physical-material.js, test/vgl-mesh-physical-material.spec.js
=> feat: new mesh physical material component.

README.md, docs/examples/geometries/vgl-lathe-geometry.html, docs/property-types.md, src/geometries/vgl-lathe-geometry.js, src/index.js, src/materials/vgl-material.js, src/parsers.js, src/validators.js, test/vgl-lathe-geometry.spec.js, test/vgl-material.spec.js
=> Add a new lathe geometry component

README.md, docs/examples/lights/vgl-hemisphere-light.html, src/index.js, src/lights/vgl-hemisphere-light.js, test/vgl-hemisphere-light.spec.js
=> feat: add a new hemisphere light component.

README.md, docs/examples/helpers/vgl-rect-area-light-helper.html, docs/examples/lights/vgl-rect-area-light.html, src/helpers/vgl-rect-area-light-helper.js, src/index.js, src/lights/vgl-rect-area-light.js, src/three.js, test/vgl-rect-area-light-helper.spec.js, test/vgl-rect-area-light.spec.js
Please let me know if there are any issues!
This should close #193
=> add RectAreaLight support via vgl-rect-area-light

README.md
=> Fix links to src files

docs/property-types.md, src/mixins.js, src/objects/vgl-mesh.js, src/validators.js
My feature request [(https://github.com/vue-gl/vue-gl/issues/538)](https://github.com/vue-gl/vue-gl/issues/538).
Here is my forked solution (Tested and working)
=> array of material on mesh

docs/property-types.md, src/parsers.js, src/scenes/vgl-scene.js, src/validators.js, test/scenes/vgl-scene.spec.js
Feature asked in this [issue](https://github.com/vue-gl/vue-gl/issues/540)
[vgl-scene]:
- new props : fog
- new props : backgroundColor
- new props : backgroundTexture
- new unit tests on init and changing props
=> Scene fog and background

.editorconfig, .gitattributes, .gitignore
This Pull Request is about improving multi environment development.
- .gitattributes will specify to Git the end-of-line of every file to 'LF' (Windows and Unix)
- .editorconfig specifies to modern IDE the required layout configuration for the projet (indent_style, indent_size, EOL etc...).
It's based on [EditorConfig.org](https://editorconfig.org/) and very convenient if we use different IDE
- .gitignore is updated to exclude JetBrains IDE folders (.idea)
=> Improve multi-env development

README.md
** Purpose of this PR
Forgot to update ExtrudeGeomtry checkbox in the README.md 😅
=> [README] Update for ExtrudeGeometry

.github/release-drafter.yml
Automate drafting releases from PRs.
=> Install release drafter

docs/rollup-plugins/rollup-plugin-generate-component-documents.js
* Page title
* Fix the error on rebuilding API documents
=> Maintain document generation

.github/workflows/publish.yml
=> Fix error on publishing documentation

package.json, src/materials/vgl-material.js, test/materials/vgl-material.spec.js, yarn.lock
* `vertexColors` property of Material is now a boolean value.
=> Update three version to 0.116.1 and follow changes

.circleci/config.yml
* New config version (2.1)
* Using reusable commands
* Hierarchical cache strategy
=> Simplify CI workflows

docs/_examples/geometries/vgl-shape-geometry.vue, docs/_examples/index.js, src/geometries/vgl-extrude-geometry.js, src/geometries/vgl-shape-geometry.js, src/index.js, src/mixins.js, test/geometries/vgl-shape-geometry.spec.js
Featuring the new VglShapeGeometry component corresponding to THREE.ShapeBufferGeometry.
Resolves #186
=> VglShapeGeometry component

docs/_examples/geometries/vgl-polyhedron-geometry.vue, docs/_examples/index.js, docs/prop-types/int-array.md, src/geometries/vgl-polyhedron-geometry.js, src/index.d.ts, src/index.js, src/parsers.js, src/types.js, src/validators.js, test/geometries/vgl-polyhedron-geometry.spec.js, test/parsers.spec.js, test/validators.spec.js
=> Adding VglPolyhedronGeometry component

src/mixins.js, test/objects/vgl-mesh.spec.js
=> Fix an error on beforeDestroy hook when the material prop is not defined

src/core/vgl-geometry.js, src/core/vgl-namespace.js, src/core/vgl-object3d.js, src/extras/vgl-curve.js, src/materials/vgl-material.js, src/textures/vgl-texture.js, test/core/vgl-geometry.spec.js, test/core/vgl-namespace.spec.js, test/core/vgl-object3d.spec.js, test/extras/vgl-shape.spec.js, test/materials/vgl-material.spec.js, test/textures/vgl-texture.spec.js
* VglNamespace accepts the `tag` prop that determines what element should be rendered as real dom.
* Invisible components rendered as template elements.
=> Tag name of components

src/textures/vgl-texture.js
=> fix: removes SphericalRefrectionMapping constant
